# version format
version: v{build}

branches:
  only:
    - master
    - deployment

# Do not build on tags
skip_tags: true

# Skipping commits with particular message or from specific user
skip_commits:
  message: "*[skip ci]*"

image: Visual Studio 2026

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  PACKAGE_PREFIX: dlebansais

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

before_build:
  - nuget restore %APPVEYOR_PROJECT_NAME%.sln
  - nuget install dlebansais.GitCommitId -DependencyVersion Highest -OutputDirectory packages
  - |-
    printf "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" > build_all.xml
    printf "  <Project xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n" >> build_all.xml
    printf "    <Target Name=\"Build\">\n" >> build_all.xml
    printf "      <MSBuild Projects=\"%APPVEYOR_PROJECT_NAME%.sln\" Properties=\"Configuration=Debug;Platform=x64\"/>\n" >> build_all.xml
    printf "      <MSBuild Projects=\"%APPVEYOR_PROJECT_NAME%.sln\" Properties=\"Configuration=Release;Platform=x64\"/>\n" >> build_all.xml
    printf "    </Target>\n" >> build_all.xml
    printf "</Project>\n" >> build_all.xml

build:
  project: build_all.xml

after_build:
  - nuget install dlebansais.Packager -DependencyVersion Highest -OutputDirectory packages # Install Packager
  - ps: $folder = Get-ChildItem -Path packages/dlebansais.Packager.* -Name | Out-String    # Get the installation folder (we don't know the actual version)
  - ps: $firstline = ($folder -split '\r\n')[0]                                            # Get rid of carriage-return
  - ps: $fullpath = ".\packages\$firstline\lib\net481\Packager.exe"                        # Build full path
  - ps: $env:PACKAGER_PATH=$fullpath
  - '%PACKAGER_PATH% %CUSTOM_PACKAGER_OPTIONS% --prefix=%PACKAGE_PREFIX%'                  # Execute the packager: the output is nuget\%PACKAGE_PREFIX%.%APPVEYOR_PROJECT_NAME%.nuspec
  - if exist nuget\%PACKAGE_PREFIX%.%APPVEYOR_PROJECT_NAME%.nuspec nuget pack nuget\%PACKAGE_PREFIX%.%APPVEYOR_PROJECT_NAME%.nuspec
  - '%PACKAGER_PATH% %CUSTOM_PACKAGER_OPTIONS% --prefix=%PACKAGE_PREFIX% --debug'          # Execute the packager: the output is nuget-debug\%PACKAGE_PREFIX%.%APPVEYOR_PROJECT_NAME%-Debug.nuspec
  - if exist nuget-debug\%PACKAGE_PREFIX%.%APPVEYOR_PROJECT_NAME%-Debug.nuspec nuget pack nuget-debug\%PACKAGE_PREFIX%.%APPVEYOR_PROJECT_NAME%-Debug.nuspec
  - ps: $xml = [xml](Get-Content .\$env:APPVEYOR_PROJECT_NAME\$env:APPVEYOR_PROJECT_NAME.csproj)
  - ps: $version=$xml.Project.PropertyGroup.Version
  - ps: set version_tag v$version
  - ps: $version_tag=$version_tag.Trim()
  - ps: $env:VERSION_TAG=$version_tag
  - echo Version is "%VERSION_TAG%"

test: off

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)/bin/x64/Release/net48/win-x64/$(APPVEYOR_PROJECT_NAME).exe
    name: $(APPVEYOR_PROJECT_NAME)
  - path: $(PACKAGE_PREFIX).$(APPVEYOR_PROJECT_NAME)-Debug.*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Debug
  - path: $(PACKAGE_PREFIX).$(APPVEYOR_PROJECT_NAME).*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Release

deploy:
  - provider: GitHub
    release: $(VERSION_TAG)
    description: 'Automatic deployment'
    auth_token:
      secure: dUpQSnUT5/m88z1BqHNnRjaxxZzz09CmyqFJr/cAyWjqKeLgnKunlIZlEKAXlNIm
    artifact: $(APPVEYOR_PROJECT_NAME)
    draft: false
    prerelease: false
    on:
      branch: deployment
  - provider: NuGet
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Release
    skip_symbols: true
    api_key:
      secure: nVIiaAk/COoMNi/OIDQ40dFBluznaIlKbpIUkxdA8HFxINY4YNkyis2sBjxByluw
    on:
      branch: deployment
      configuration: Release
  - provider: NuGet
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    symbol_server: https://api.nuget.org/v3/index.json
    api_key:
      secure: nVIiaAk/COoMNi/OIDQ40dFBluznaIlKbpIUkxdA8HFxINY4YNkyis2sBjxByluw
    on:
      branch: deployment
      configuration: Debug
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    symbol_server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    username: dlebansais
    api_key:
      secure: 7DLdeObgZf+PG3CwBCFWr2UvW6IFBF4Lwa0SUxFeQbkWr6DJSwNPFDwuKXgX8Wfy
    on:
      branch: deployment
      configuration: Debug
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Release
    skip_symbols: true
    username: dlebansais
    api_key:
      secure: 7DLdeObgZf+PG3CwBCFWr2UvW6IFBF4Lwa0SUxFeQbkWr6DJSwNPFDwuKXgX8Wfy
    on:
      branch: deployment
      configuration: Release
